//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodbyeDPI_Configurator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"manual\"")]
        public string StartUpType {
            get {
                return ((string)(this["StartUpType"]));
            }
            set {
                this["StartUpType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""Name"": ""Modern 9 (Default)"",
    ""HTTPFragmentationEnabled"": true,
    ""HTTPFragmentationValue"": 2,
    ""HTTPSFragmentationEnabled"": true,
    ""HTTPSFragmentationValue"": 2,
    ""WrongSequence"": true,
    ""WrongChecksum"": true,
    ""ReverseFragmentation"": true,
    ""MaxPayloadEnabled"": true
  }")]
        public string CurrentProfile {
            get {
                return ((string)(this["CurrentProfile"]));
            }
            set {
                this["CurrentProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\r\n  {\r\n    \"Name\": \"Legacy 1\",\r\n    \"BlockPassiveDPI\": true,\r\n    \"ReplaceHost\":" +
            " true,\r\n    \"RemoveSpaceBetweenHeaderValue\": true,\r\n    \"DontWaitForFirstAck\": t" +
            "rue,\r\n    \"HTTPFragmentationEnabled\": true,\r\n    \"HTTPFragmentationValue\": 2,\r\n " +
            "   \"PHTTPFragmentationEnabled\": true,\r\n    \"PHTTPFragmentationValue\": 2,\r\n    \"H" +
            "TTPSFragmentationEnabled\": true,\r\n    \"HTTPSFragmentationValue\": 2\r\n  },\r\n  {\r\n " +
            "   \"Name\": \"Legacy 2\",\r\n    \"BlockPassiveDPI\": true,\r\n    \"ReplaceHost\": true,\r\n" +
            "    \"RemoveSpaceBetweenHeaderValue\": true,\r\n    \"DontWaitForFirstAck\": true,\r\n  " +
            "  \"HTTPFragmentationEnabled\": true,\r\n    \"HTTPFragmentationValue\": 2,\r\n    \"PHTT" +
            "PFragmentationEnabled\": true,\r\n    \"PHTTPFragmentationValue\": 2,\r\n    \"HTTPSFrag" +
            "mentationEnabled\": true,\r\n    \"HTTPSFragmentationValue\": 40\r\n  },\r\n  {\r\n    \"Nam" +
            "e\": \"Legacy 3\",\r\n    \"BlockPassiveDPI\": true,\r\n    \"ReplaceHost\": true,\r\n    \"Re" +
            "moveSpaceBetweenHeaderValue\": true,\r\n    \"HTTPSFragmentationEnabled\": true,\r\n   " +
            " \"HTTPSFragmentationValue\": 40\r\n  },\r\n  {\r\n    \"Name\": \"Legacy 4\",\r\n    \"BlockPa" +
            "ssiveDPI\": true,\r\n    \"ReplaceHost\": true,\r\n    \"RemoveSpaceBetweenHeaderValue\":" +
            " true\r\n  },\r\n  {\r\n    \"Name\": \"Modern 5\",\r\n    \"HTTPFragmentationEnabled\": true," +
            "\r\n    \"HTTPFragmentationValue\": 2,\r\n    \"HTTPSFragmentationEnabled\": true,\r\n    " +
            "\"HTTPSFragmentationValue\": 2,\r\n    \"AutoTTLBaseTopMaxEnabled\": true,\r\n    \"Rever" +
            "seFragmentation\": true,\r\n    \"MaxPayloadEnabled\": true\r\n  },\r\n  {\r\n    \"Name\": \"" +
            "Modern 6\",\r\n    \"HTTPFragmentationEnabled\": true,\r\n    \"HTTPFragmentationValue\":" +
            " 2,\r\n    \"HTTPSFragmentationEnabled\": true,\r\n    \"HTTPSFragmentationValue\": 2,\r\n" +
            "    \"WrongSequence\": true,\r\n    \"ReverseFragmentation\": true,\r\n    \"MaxPayloadEn" +
            "abled\": true\r\n  },\r\n  {\r\n    \"Name\": \"Modern 7\",\r\n    \"HTTPFragmentationEnabled\"" +
            ": true,\r\n    \"HTTPFragmentationValue\": 2,\r\n    \"HTTPSFragmentationEnabled\": true" +
            ",\r\n    \"HTTPSFragmentationValue\": 2,\r\n    \"WrongChecksum\": true,\r\n    \"ReverseFr" +
            "agmentation\": true,\r\n    \"MaxPayloadEnabled\": true\r\n  },\r\n  {\r\n    \"Name\": \"Mode" +
            "rn 8\",\r\n    \"HTTPFragmentationEnabled\": true,\r\n    \"HTTPFragmentationValue\": 2,\r" +
            "\n    \"HTTPSFragmentationEnabled\": true,\r\n    \"HTTPSFragmentationValue\": 2,\r\n    " +
            "\"WrongSequence\": true,\r\n    \"WrongChecksum\": true,\r\n    \"ReverseFragmentation\": " +
            "true,\r\n    \"MaxPayloadEnabled\": true\r\n  },\r\n  {\r\n    \"Name\": \"Modern 9 (Default)" +
            "\",\r\n    \"HTTPFragmentationEnabled\": true,\r\n    \"HTTPFragmentationValue\": 2,\r\n   " +
            " \"HTTPSFragmentationEnabled\": true,\r\n    \"HTTPSFragmentationValue\": 2,\r\n    \"Wro" +
            "ngSequence\": true,\r\n    \"WrongChecksum\": true,\r\n    \"ReverseFragmentation\": true" +
            ",\r\n    \"MaxPayloadEnabled\": true\r\n  }\r\n]")]
        public string Profiles {
            get {
                return ((string)(this["Profiles"]));
            }
            set {
                this["Profiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string KillWinDivert {
            get {
                return ((string)(this["KillWinDivert"]));
            }
            set {
                this["KillWinDivert"] = value;
            }
        }
    }
}
